import { Sidebar } from "@/components/dashboard/Sidebar"
const navItems = [
  { label: 'Overview', href: '/home' },
];

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Sidebar items={navItems} />
        {children}
      </body>
    </html>
  )
}
